/**
 * TestGenerationValidator
 *
 * PURPOSE
 * -------
 * This component validates BOTH:
 *
 * 1) Test draft BEFORE generation begins
 * 2) TestQuestion objects AFTER they are generated by the LLM
 *
 * It acts as a safety and integrity gate for the entire test generation lifecycle.
 *
 *
 * VALIDATION PHASES
 * -----------------
 *
 * PHASE 1 — Test draft validation (PRE-GENERATION)
 * -----------------------------------------------
 * Ensures that the Test configuration is valid and safe to use for generation.
 *
 * This includes:
 *
 * - Test object must not be null
 * - At least one topicId or documentId must be specified
 * - questionCount must be > 0
 * - All referenced topics must exist and belong to tenant
 * - All referenced documents must exist and belong to tenant
 * - All source documents (explicit and resolved from topics) must be in INGESTED state
 * - Ensures that generation will have valid and usable source content
 *
 * This phase prevents invalid generation attempts early and avoids wasted LLM calls.
 *
 *
 * PHASE 2 — Generated question validation (POST-GENERATION)
 * ---------------------------------------------------------
 * Ensures structural integrity, quality, and safety of LLM output.
 *
 * Since LLM output is probabilistic, questions may be malformed, incomplete, or duplicated.
 *
 * This phase performs:
 *
 * - Question text validation and normalization
 * - Option validation (mandatory options present)
 * - Correct answer validation
 * - Explanation validation (optional, configurable)
 * - Grounding metadata validation (optional, configurable)
 * - Duplicate question detection and removal
 * - Invalid grounding chunkIds removal
 * - Question index normalization
 * - questionCount limit enforcement
 *
 *
 * DESIGN PRINCIPLES
 * -----------------
 *
 * Separation of responsibilities:
 *
 * - Retrieval logic belongs to VectorStore
 * - Persistence belongs to transactional service
 * - Prompt construction belongs to TestPromptBuilder
 * - This validator ensures structural integrity and safety only
 *
 *
 * SAFETY POLICY
 * -------------
 *
 * This validator NEVER attempts risky auto-correction such as:
 *
 * - guessing correct answers
 * - shifting options automatically
 * - inventing missing grounding
 *
 * Invalid questions are rejected safely.
 *
 *
 * CONFIGURATION FLAGS
 * -------------------
 *
 * requireAllFourOptions
 *      true  → strict MCQ mode (A–D required)
 *      false → allows fewer options (minimum A and B)
 *
 * requireExplanation
 *      true  → explanation required
 *      false → explanation optional
 *
 * requireGrounding
 *      true  → sourceChunkIdsJson must be present and valid
 *      false → grounding optional
 *
 *
 * THREAD SAFETY
 * -------------
 * Stateless and thread-safe.
 *
 *
 * ARCHITECTURAL ROLE
 * ------------------
 * Core domain service component.
 *
 * Used by TestGenerationServiceImpl during generation lifecycle.
 *
 */
